// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nlqjlqdecfjmwcttlivw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5scWpscWRlY2ZqbXdjdHRsaXZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyOTQ1MDEsImV4cCI6MjA2ODg3MDUwMX0.dyY_uNBZCX8XA8p4WAJXjXW6FwITn5C5iV62OiiXYZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});